Repository go-vela/pkg-runtime, pull requests merged in 2020-03, with the labels that each got.

#4 improvement: create working cli
  cmd/vela-runtime/pipeline.go
  cmd/vela-runtime/resource.go
  cmd/vela-runtime/run.go
  go.mod
  go.sum
  runtime/kubernetes/container.go
  runtime/kubernetes/kubernetes.go
  runtime/kubernetes/network.go
  runtime/kubernetes/volume.go
  testdata/steps.yml
Labels: enhancement

#5 feat: add container wait implementation for kubernetes
  cmd/vela-runtime/run.go
  runtime/kubernetes/container.go
  testdata/steps.yml
Labels: enhancement

#6 feat(kubernetes): add tail functionality
  cmd/vela-runtime/run.go
  runtime/kubernetes/container.go
  runtime/kubernetes/kubernetes.go
  testdata/steps.yml
Labels: feature

#7 improvement(kubernetes): use default patch type
  runtime/kubernetes/container.go
  runtime/kubernetes/image.go
  runtime/kubernetes/kubernetes.go
  runtime/kubernetes/network.go
  runtime/kubernetes/volume.go
Labels: enhancement

#8 feat(kubernetes): add logic to remove resources
  cmd/vela-runtime/run.go
  runtime/kubernetes/container.go
  runtime/kubernetes/network.go
  runtime/kubernetes/volume.go
Labels: feature

#10 feat: implement the inspect process for kubernetes
  cmd/vela-runtime/run.go
  runtime/kubernetes/container.go
  testdata/steps.yml
Labels: enhancement

#12 feat: add func for new runtime
  Makefile
  cmd/vela-runtime/main.go
  cmd/vela-runtime/run.go
  cmd/vela-runtime/runtime.go
  runtime/engine.go
  runtime/runtime.go
Labels: feature

#13 feat: add validate logic for setup
  runtime/doc.go
  runtime/runtime.go
  runtime/setup.go
Labels: feature

#14 ci: add github actions pipeline
  .github/README.md
  .github/workflows/build.yml
  .github/workflows/release.yml
  .github/workflows/test.yml
  .github/workflows/validate.yml
  codecov.yml
  runtime/docker/container.go
Labels: feature

#15 feat: update docker structs to be saved to client
  Makefile
  cmd/vela-runtime/run.go
  runtime/docker/container.go
  runtime/docker/container_test.go
  runtime/docker/docker.go
  runtime/docker/volume.go
  runtime/engine.go
  runtime/kubernetes/container.go
Labels: Do Not Merge, enhancement

#16 docs: move license badge to top of readme
  .github/README.md
  LICENSE
Labels: enhancement

#17 chore: add unit tests for kubernetes runtime
  go.sum
  runtime/kubernetes/container.go
  runtime/kubernetes/container_test.go
  runtime/kubernetes/image_test.go
  runtime/kubernetes/kubernetes.go
  runtime/kubernetes/network.go
  runtime/kubernetes/network_test.go
  runtime/kubernetes/volume.go
  runtime/kubernetes/volume_test.go
Labels: enhancement

#19 chore: improve docker tests to 90%
  runtime/docker/container_test.go
  runtime/docker/docker.go
  runtime/docker/docker_test.go
Labels: enhancement

#20 chore: add tests for kubernetes client
  runtime/kubernetes/kubernetes.go
  runtime/kubernetes/kubernetes_test.go
  runtime/kubernetes/testdata/config
  runtime/kubernetes/testdata/config_empty
Labels: enhancement

#21 feat(runtime): add exported CLI flags
  cmd/vela-runtime/flags.go
  cmd/vela-runtime/main.go
  runtime/flags.go
Labels: feature

#22 docs(docker): add links to godoc
  runtime/docker/container.go
  runtime/docker/docker.go
  runtime/docker/image.go
  runtime/docker/network.go
  runtime/docker/volume.go
Labels: enhancement

#23 chore: sync logging between runtimes
  runtime/docker/container.go
  runtime/docker/docker.go
  runtime/docker/image.go
  runtime/docker/network.go
  runtime/docker/volume.go
  runtime/kubernetes/container.go
  runtime/kubernetes/image.go
  runtime/kubernetes/network.go
  runtime/kubernetes/volume.go
Labels: enhancement

#24 test(runtime): add 100% coverage
  runtime/context.go
  runtime/context_test.go
  runtime/flags.go
  runtime/runtime.go
  runtime/runtime_test.go
  runtime/setup_test.go
Labels: enhancement

#25 test(docker): convert to new mock library
  go.mod
  go.sum
  runtime/docker/container.go
  runtime/docker/container_test.go
  runtime/docker/docker.go
  runtime/docker/docker_test.go
  runtime/docker/image_test.go
  runtime/docker/network_test.go
  runtime/docker/volume_test.go
Labels: enhancement

#26 chore(docker): remove old mock
  go.mod
  go.sum
  runtime/docker/container_test.go
  runtime/docker/testdata/mock/container.go
  runtime/docker/testdata/mock/docker.go
  runtime/docker/testdata/mock/images.go
  runtime/docker/testdata/mock/network.go
  runtime/docker/testdata/mock/volume.go
Labels: enhancement
