Repository go-vela/pkg-runtime, pull requests merged in 2020-07, with the labels that each got.

#49 ci: refactor Makefile. improve linter setup. upgrade deps.
  .github/workflows/build.yml
  .github/workflows/release.yml
  .github/workflows/reviewdog.yml
  .github/workflows/test.yml
  .github/workflows/validate.yml
  .golangci.yml
  Makefile
  codecov.yml
  go.mod
  go.sum
Labels: dependencies, enhancement

#50 enhancement: return full inspect data
  cmd/vela-runtime/run.go
  runtime/docker/network.go
  runtime/docker/volume.go
Labels: enhancement

#51 chore: update go mod for v0.5.0-rc1
  go.mod
  go.sum
Labels: dependencies
