Repository go-vela/pkg-runtime, pull requests merged in 2020-09, with the labels that each got.

#56 feat: add support for container pull policies
  go.mod
  go.sum
  runtime/docker/container.go
  runtime/docker/container_test.go
  runtime/docker/docker_test.go
  runtime/docker/image.go
  runtime/docker/image_test.go
  runtime/engine.go
  runtime/kubernetes/container.go
  runtime/kubernetes/container_test.go
  runtime/kubernetes/image.go
  runtime/kubernetes/kubernetes_test.go
Labels: dependencies, feature

#57 fix: skip image inspect for on_start pull policy
  runtime/docker/image.go
Labels: bug

#58 release: updates for v0.6.0-rc1
  go.mod
  go.sum
Labels: dependencies

#59 release: updates for v0.6.0-rc2
  go.mod
  go.sum
Labels: dependencies

#60 release: updates for v0.6.0
  go.mod
  go.sum
Labels: dependencies
