Repository go-vela/pkg-runtime, pull requests merged in 2020-04, with the labels that each got.

#27 refactor: make vendor client private
  runtime/docker/container.go
  runtime/docker/docker.go
  runtime/docker/image.go
  runtime/docker/network.go
  runtime/docker/volume.go
  runtime/kubernetes/container.go
  runtime/kubernetes/kubernetes.go
Labels: enhancement

#28 test(kubernetes): refactor for table tests
  runtime/kubernetes/container.go
  runtime/kubernetes/container_test.go
  runtime/kubernetes/image_test.go
  runtime/kubernetes/kubernetes.go
  runtime/kubernetes/kubernetes_test.go
  runtime/kubernetes/network_test.go
  runtime/kubernetes/volume_test.go
Labels: enhancement

#29 feat(runtime): add package for parsing images
  runtime/docker/container.go
  runtime/docker/image.go
  runtime/internal/doc.go
  runtime/internal/image/doc.go
  runtime/internal/image/image.go
  runtime/internal/image/image_test.go
  runtime/internal/internal.go
  runtime/kubernetes/container.go
  runtime/kubernetes/image.go
Labels: feature

#30 refactor(internal): move pkg to repo root
  internal/doc.go
  internal/image/doc.go
  internal/image/image.go
  internal/image/image_test.go
  internal/internal.go
  runtime/docker/container.go
  runtime/docker/image.go
  runtime/docker/network.go
  runtime/internal/internal.go
  runtime/kubernetes/container.go
Labels: enhancement

#31 refactor(testdata): move into single folder
  cmd/vela-runtime/flags.go
  runtime/testdata/large.yml
  runtime/testdata/stages.yml
  runtime/testdata/steps.yml
  testdata/steps_100.yml
  testdata/steps_1000.yml
Labels: enhancement

#32 test(kubernetes): add WaitContainer tests
  runtime/kubernetes/container_test.go
  runtime/kubernetes/kubernetes.go
  runtime/kubernetes/kubernetes_test.go
Labels: enhancement

#34 docs(runtime): add pkg.go.dev links
  runtime/flags.go
  runtime/runtime.go
  runtime/setup.go
Labels: enhancement

#35 chore: update for v0.4.0-rc1
  go.mod
  go.sum
Labels: dependencies

#36 chore: update dependencies for v0.4.0-rc2
  go.mod
  go.sum
Labels: dependencies

#38 chore: update version to v0.4.0-rc3
  go.mod
  go.sum
Labels: dependencies
