Repository go-vela/pkg-runtime, pull requests merged in 2020-11, with the labels that each got.

#64 fix: skip closing read buffer and manually close other buffers
  runtime/docker/container.go
Labels: bug

#63 chore: upgrade Docker API and client
  go.mod
  go.sum
  runtime/docker/docker.go
Labels: enhancement

#62 feat: add allow list for privileged containers
  internal/image/image.go
  internal/image/image_test.go
  runtime/docker/container.go
  runtime/docker/container_test.go
  runtime/docker/docker.go
  runtime/docker/docker_test.go
  runtime/flags.go
  runtime/kubernetes/container.go
  runtime/kubernetes/container_test.go
  runtime/kubernetes/kubernetes.go
  runtime/kubernetes/kubernetes_test.go
  runtime/setup.go
Labels: feature
