Repository go-vela/pkg-runtime, pull requests merged in 2021-02, with the labels that each got.

#86 chore: linter setup and fixes, doc changes
  .github/CONTRIBUTING.md
  .golangci.yml
  cmd/vela-runtime/resource.go
  cmd/vela-runtime/run.go
  internal/volume/volume.go
  runtime/context.go
  runtime/context_test.go
  runtime/docker/container.go
  runtime/docker/docker.go
  runtime/docker/docker_test.go
  runtime/kubernetes/container.go
  runtime/kubernetes/kubernetes.go
  runtime/kubernetes/kubernetes_test.go
  runtime/kubernetes/network.go
  runtime/runtime.go
Labels: enhancement

#87 chore: upgrade go-vela deps on v0.7.0
  go.mod
  go.sum
Labels: dependencies

#98 fix(volumes): actually allocate new host config with volume data
  runtime/docker/container.go
Labels: bug
